/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tdes_TDES */

#ifndef _Included_tdes_TDES
#define _Included_tdes_TDES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tdes_TDES
 * Method:    pruebaConexion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TDES_pruebaConexion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
