/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tdes_TDES */

#ifndef _Included_tdes_TDES
#define _Included_tdes_TDES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tdes_TDES
 * Method:    pruebaConexion
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT int JNICALL Java_tdes_TDES_pruebaConexion
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
